version: "3.5"
services:
  backend:
    container_name: backend
    image: backend
    build: ./
    links:
      - database
    env_file:
      - .env
    environment:
      - DB_IP=database
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
