version: "3.5"
services:
  backend:
    container_name: backend
    image: backend
    build: ./
    links:
      - database
    ports:
      - "80:80"
    environment:
      - DB_IP=database
    depends_on:
      - database
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
